export type MenuItem = { name: string; price: string };
export type MenuSection = { key: string; note?: string; items: MenuItem[] };

export const menuSections: MenuSection[] = [
  { key: "brunch", note: "έως 16:00", items: [
    { name: "Benedict με Σολομό", price: "9.5" },
    { name: "Benedict με Μανούρι και Μανιτάρια", price: "8.7" },
    { name: "Benedict με Γαλοπούλα", price: "8.9" },
    { name: "Breakfast Egg Wrap", price: "8.2" },
    { name: "Croque Madame", price: "8" },
  ]},
  { key: "openToast", items: [
    { name: "Αυγά Scrambled", price: "5" },
    { name: "Σολομός", price: "6.4" },
    { name: "Κοτόπουλο", price: "6" },
    { name: "Savory Avocado", price: "6" },
    { name: "Sweet Avocado", price: "5.5" },
    { name: "Healthy Sweet", price: "5.5" },
  ]},
  { key: "pancakes", items: [
    { name: "Bueno", price: "6.4" },
    { name: "Lila Pause", price: "6.5" },
    { name: "Classic", price: "6" },
    { name: "Sneakers", price: "6.5" },
    { name: "Φυστικοβούτυρο", price: "6" },
    { name: "Φυστικοβούτυρο - Κακάο", price: "6" },
    { name: "Pancakes Oreo", price: "6.5" },
    { name: "Plastelina Pan Club", price: "8.5" },
    { name: "Egg", price: "8" },
  ]},
  { key: "omelettes", note: "έως 16:00", items: [
    { name: "Γαλοπούλα", price: "7.5" },
    { name: "Καγιανάς", price: "7" },
  ]},
  { key: "salads", items: [
    { name: "Κοτόπουλο", price: "8.5" },
    { name: "Ροδί", price: "8" },
    { name: "Κινόα", price: "9.5" },
  ]},
  { key: "pasta", note: "από 13:00", items: [
    { name: "Pasta με Κοτόπουλο", price: "8.5" },
    { name: "Pasta Carbonara", price: "8.5" },
    { name: "Nioki", price: "8.5" },
    { name: "Nioki Κοτόπουλο", price: "9.5" },
    { name: "Ravioli", price: "9.5" },
    { name: "Risoto Μανιταριών", price: "8.5" },
  ]},
  { key: "burgers", note: "από 13:00", items: [
    { name: "Cheeseburger", price: "8.9" },
    { name: "Chicken Burger", price: "8.5" },
  ]},
  { key: "main", note: "13:00–23:00", items: [
    { name: "Μπαλοτίνα Κοτόπουλο", price: "10" },
    { name: "Κοτόπουλο Φιλέτο", price: "9.2" },
    { name: "Κοτόπουλο Πανέ", price: "9.4" },
    { name: "Ψαρονέφρι", price: "9.5" },
  ]},
  { key: "pinsa", items: [
    { name: "Προσούτο", price: "10.5" },
    { name: "Ελληνική Vegetarian", price: "10" },
    { name: "Πεπερόνι", price: "11.5" },
  ]},
  { key: "yogurt", items: [
    { name: "Granola", price: "6" },
    { name: "Superfood", price: "6" },
    { name: "Μπανάνα Bowl", price: "8" },
    { name: "Μήλο Bowl", price: "8" },
    { name: "Acai", price: "8" },
    { name: "Dragon Bowl", price: "7" },
    { name: "Chipotle Tahini Bowl", price: "8" },
    { name: "Bowl με Λαχανικά", price: "8" },
  ]},
  { key: "smoothies", items: [
    { name: "Hazelnut", price: "6" },
    { name: "High Protein", price: "6.5" },
    { name: "Energy", price: "6" },
    { name: "Fitness", price: "6" },
  ]},
  { key: "street", items: [
    { name: "Τορτίγια Κοτόπουλο Light", price: "7.2" },
    { name: "Τορτίγια Κοτόπουλο BBQ", price: "7.5" },
    { name: "Katsu Sando Καραμελωμένη Πανσέτα", price: "8.5" },
    { name: "Katsu Sando Κοτόπουλο Πανέ", price: "8.5" },
    { name: "Πατάτες Τηγανιτές", price: "4" },
    { name: "Πατάτες Τηγανιτές με Bacon", price: "5" },
  ]},
  { key: "bagels", items: [
    { name: "Προσούτο", price: "5.8" },
    { name: "Σολομός", price: "6" },
    { name: "Salami Milano", price: "5.8" },
    { name: "Χωριάτικο", price: "5.5" },
  ]},
  { key: "desserts", items: [
    { name: "Μιλφέιγ", price: "7" },
  ]},
  { key: "coffee", note: "Cortese Caffè", items: [
    { name: "Cold Brew", price: "5 / 5.2" },
    { name: "Espresso", price: "2.3 / 2.5" },
    { name: "Espresso Ristretto", price: "2.3 / 2.5" },
    { name: "Espresso Lungo", price: "2.3 / 2.5" },
    { name: "Double Americano", price: "3.2" },
    { name: "Espresso Doppio", price: "3.5 / 3.7" },
    { name: "Cappuccino", price: "3.5 / 3.7" },
    { name: "Double Cappuccino", price: "4.2" },
    { name: "Flat White", price: "4 / 4.2" },
    { name: "Freddo Flat White", price: "4 / 4.2" },
    { name: "Latte", price: "4 / 4.2" },
    { name: "Freddo Espresso", price: "3.8 / 4" },
    { name: "Freddo Cappuccino", price: "3.8 / 4" },
    { name: "Freddo Latte", price: "3.8 / 4" },
    { name: "Ελληνικός Μονός", price: "2.5" },
    { name: "Ελληνικός Διπλός", price: "3.5" },
    { name: "Φίλτρου", price: "3.8" },
    { name: "Σοκολάτα", price: "4" },
    { name: "Σοκολάτα με Γεύσεις", price: "4.5" },
  ]},
  { key: "drinks", items: [
    { name: "Coca-Cola", price: "3" },
    { name: "Coca-Cola Zero", price: "3" },
    { name: "Fanta Πορτοκαλάδα", price: "3" },
    { name: "Fanta Λεμονάδα", price: "3" },
    { name: "Sprite", price: "3" },
    { name: "Three Cents — Tonic Water", price: "4.5" },
    { name: "Three Cents — Pink Grapefruit", price: "4.5" },
    { name: "Three Cents — Ginger Beer", price: "4.5" },
    { name: "Bud Draught", price: "5" },
    { name: "Stella Artois", price: "6" },
    { name: "Corona", price: "6" },
    { name: "Franziskaner Weiss", price: "7" },
    { name: "Leffe Brune", price: "6" },
    { name: "Μηλοκλέφτης", price: "5" },
    { name: 'Solo "Ψάκι"', price: "6" },
    { name: 'Solo "Φουριάρης"', price: "7" },
  ]},
  { key: "wine", items: [
    { name: "Λευκά — House White (γυάλα)", price: "5" },
    { name: "Λευκά — Ασύρτικο Σαντορίνης", price: "32" },
    { name: "Λευκά — Μοσχοφίλερο", price: "22" },
    { name: "Ροζέ — House Rosé", price: "5" },
    { name: "Ροζέ — Αγιωργίτικο Rosé", price: "24" },
    { name: "Ερυθρά — House Red", price: "5" },
    { name: "Ερυθρά — Αγιωργίτικο Νεμέας", price: "26" },
    { name: "Ερυθρά — Cabernet Sauvignon", price: "30" },
    { name: "Αφρώδη — Prosecco", price: "28" },
    { name: "Αφρώδη — Champagne Brut", price: "65" },
  ]},
];
